### ISSUE TITLE
strange default that include developer username

### ISSUE THREAD

**Issue by camelop** [CoLearn-Dev/rdbc2#2]
https://github.com/CoLearn-Dev/rdbc2/blob/746a580c66c7207a61d72059bb5d752e4cad4d66/tests/mysql_test.rs#L13

**Comment by nociza** [comment]
Removed!

**Comment by camelop** [comment]
Uh... still there?
https://github.com/CoLearn-Dev/rdbc2/blob/35089ba9bf39f339dfd645224529bc2ec19ed5e3/tests/mysql_test.rs#L11

**Comment by nociza** [comment]
Now its really removed
