### ISSUE TITLE
Question: why the preparation of database in mysql is different from the one in sqlite

### ISSUE THREAD

**Issue by camelop** [CoLearn-Dev/rdbc2#5]
https://github.com/CoLearn-Dev/rdbc2/blob/746a580c66c7207a61d72059bb5d752e4cad4d66/tests/mysql_test.rs#L17

Also, does this mean when using rdbc2, the user need to set up the table differently? (This might be fine but just curious)

**Comment by nociza** [comment]
No no, the table can be anything SQL. The function is for cleaning the database and also I'm using some MySQL-specific commands like "CREATE TABLE IF NOT EXIST" to simplify stuff.

**Comment by camelop** [comment]
Oh in that case, maybe we should find a set of commands that works for every db impl as the example, so that it's convenient for people to just learn from this repo for a best practice?

**Comment by camelop** [comment]
jdbc also has the same problem, closing
