### ISSUE TITLE
Is it true that `affected_rows == rows.len()`?

### ISSUE THREAD

**Issue by camelop** [CoLearn-Dev/rdbc2#7]
https://github.com/CoLearn-Dev/rdbc2/blob/746a580c66c7207a61d72059bb5d752e4cad4d66/src/dbc.rs#L133-L134

If so, consider removing the redundant variable; if not, consider using a more informative variable name and add comments to explain

**Comment by nociza** [comment]
Actually affected rows is for commands that are not query, such as update or create. This is because mysql and sqlite both has this to indicate how many rows are affected from the command.

**Comment by camelop** [comment]
I see. In that case, it would be nice to clarify this somewhere.

**Comment by nociza** [comment]
Renamed to `affected_row_count`
